### ISSUE TITLE
OpenTK issue in versions >2.0

### ISSUE THREAD

**Issue by Freiling87** [FaronBracy/RogueSharpRLNetSamples#3]
> System.MissingMethodException
>   HResult=0x80131513
>   Message=Method not found: 'Void OpenTK.Graphics.OpenGL.GL.BlendFunc(OpenTK.Graphics.OpenGL.BlendingFactorSrc, OpenTK.Graphics.OpenGL.BlendingFactorDest)'.
>   Source=RLNET
>   StackTrace:
>    at RLNET.RLRootConsole.Draw()
>    at FuRL.Game.OnRootConsoleRender(Object sender, UpdateEventArgs e) in C:\TWL\CODING\FuRL\Game.cs:line 157
>    at RLNET.RLRootConsole.window_RenderFrame(Object sender, FrameEventArgs e)
>    at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
>    at OpenTK.GameWindow.OnRenderFrame(FrameEventArgs e)
>    at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
>    at OpenTK.GameWindow.DispatchRenderFrame()
>    at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
>    at OpenTK.GameWindow.Run(Double updateRate)
>    at RLNET.RLRootConsole.Run(Double fps)
>    at FuRL.Game.Main() in C:\TWL\CODING\FuRL\Game.cs:line 71

**Comment by Freiling87** [comment]
Reverted to OpenTK 2.0, issue resolved.
